### ISSUE TITLE
Bug: express-stormpath is incompatible with node streams (request.pipe and http-proxy)

### ISSUE THREAD

**Issue by baer** [stormpath/express-stormpath#180]
express-stormpath is crashing my application when I `POST` to a proxied route in express regardless of whether or not it is protected by`stormpath.loginRequired`. Removing the `app.use` in my express config fixes the problem. 

I will keep looking into the issue and will continually update as I find things.

```js
$.ajax({
  url: 'api/aRouteToPostTo',
  type: 'POST',
  data: savableOrder,
  dataType: 'json'
});
```

```js
app.all('/api/*', function(req, res) {
  req.url = req.url.slice(5, req.url.length);
  req.url = '/myApiRootUrl/' + req.url;

  var auth = 'Basic ' + new Buffer(config.proxyUsername + ':' + config.proxyPassword).toString('base64');
  req.headers.authorization = auth;

  proxy.web(req, res, {
    target: 'http://' + config.proxyHost + ':' + config.proxyPort
  });
});
```

```js
app.use(stormpath.init(app, {
  website: true,
  client: {
    apiKey: {
      id: config.stormpath.id,
      secret: config.stormpath.secret
    }
  },
  application: {
    href: config.stormpath.url
  },
  web: {
    register: {
      fieldOrder: ['givenName', 'surname', 'email', 'password', 'passwordConfirm']
    }
  }
}));
```
```
POST /api/aRouteToPostTo - - ms - -
Error: socket hang up
    at createHangUpError (_http_client.js:209:15)
    at Socket.socketCloseListener (_http_client.js:241:23)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
---------------------------------------------
    at Array.stream (/Users/xxxxxx/dev/stormpath-app/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:134:14)
    at ProxyServer.<anonymous> (/Users/xxxxxx/dev/stormpath-app/node_modules/http-proxy/lib/http-proxy/index.js:80:21)
    at /Users/xxxxxx/dev/stormpath-app/src/server/routes.js:52:11
    at Layer.handle [as handle_request] (/Users/xxxxxx/dev/stormpath-app/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/xxxxxx/dev/stormpath-app/node_modules/express/lib/router/route.js:131:13)
    at next (/Users/xxxxxx/dev/stormpath-app/node_modules/express/lib/router/route.js:125:14)
    at next (/Users/xxxxxx/dev/stormpath-app/node_modules/express/lib/router/route.js:125:14)
    at next (/Users/xxxxxx/dev/stormpath-app/node_modules/express/lib/router/route.js:125:14)
    at next (/Users/xxxxxx/dev/stormpath-app/node_modules/express/lib/router/route.js:125:14)
---------------------------------------------
    at Request.init (/Users/xxxxxx/dev/stormpath-app/node_modules/stormpath/node_modules/request/request.js:126:10)
    at new Request (/Users/xxxxxx/dev/stormpath-app/node_modules/stormpath/node_modules/request/request.js:99:8)
    at request (/Users/xxxxxx/dev/stormpath-app/node_modules/stormpath/node_modules/request/index.js:54:11)
    at RequestExecutor.executeRequest [as execute] (/Users/xxxxxx/dev/stormpath-app/node_modules/stormpath/lib/ds/RequestExecutor.js:92:3)
    at doRequest (/Users/xxxxxx/dev/stormpath-app/node_modules/stormpath/lib/ds/DataStore.js:277:27)
    at onCacheResult (/Users/xxxxxx/dev/stormpath-app/node_modules/stormpath/lib/ds/DataStore.js:301:5)
    at Array.<anonymous> (/Users/xxxxxx/dev/stormpath-app/node_modules/stormpath/lib/cache/Cache.js:54:14)
    at DisabledCache.get.DisabledCache.set.DisabledCache.delete.DisabledCache.clear.DisabledCache.size (/Users/xxxxxx/dev/stormpath-app/node_modules/stormpath/lib/cache/DisabledCache.js:11:62)
    at Cache.get (/Users/xxxxxx/dev/stormpath-app/node_modules/stormpath/lib/cache/Cache.js:52:14)
---------------------------------------------
    at handleError (/Users/xxxxxx/dev/stormpath-app/node_modules/njwt/index.js:56:20)
    at Verifier.verify (/Users/xxxxxx/dev/stormpath-app/node_modules/njwt/index.js:352:12)
    at Object.jwtLib.verify (/Users/xxxxxx/dev/stormpath-app/node_modules/njwt/index.js:388:21)
    at JwtAuthenticator.authenticate (/Users/xxxxxx/dev/stormpath-app/node_modules/stormpath/lib/jwt/jwt-authenticator.js:40:8)
    at Object.module.exports [as getUser] (/Users/xxxxxx/dev/stormpath-app/node_modules/express-stormpath/lib/helpers/get-user.js:69:19)
    at stormpathMiddleware (/Users/xxxxxx/dev/stormpath-app/node_modules/express-stormpath/lib/stormpath.js:92:13)
    at Layer.handle [as handle_request] (/Users/xxxxxx/dev/stormpath-app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/xxxxxx/dev/stormpath-app/node_modules/express/lib/router/index.js:312:13)
    at /Users/xxxxxx/dev/stormpath-app/node_modules/express/lib/router/index.js:280:7
---------------------------------------------
    at IncomingMessage.Readable.on (_stream_readable.js:665:33)
    at readStream (/Users/xxxxxx/dev/stormpath-app/node_modules/raw-body/index.js:231:10)
    at getRawBody (/Users/xxxxxx/dev/stormpath-app/node_modules/raw-body/index.js:106:12)
    at read (/Users/xxxxxx/dev/stormpath-app/node_modules/body-parser/lib/read.js:76:3)
    at urlencodedParser (/Users/xxxxxx/dev/stormpath-app/node_modules/body-parser/lib/types/urlencoded.js:109:5)
    at Layer.handle [as handle_request] (/Users/xxxxxx/dev/stormpath-app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/xxxxxx/dev/stormpath-app/node_modules/express/lib/router/index.js:312:13)
    at /Users/xxxxxx/dev/stormpath-app/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/xxxxxx/dev/stormpath-app/node_modules/express/lib/router/index.js:330:12)
```

**Comment by baer** [comment]
Updated to reflect new information - `POST`s do not work on any route regardless of whether it is guarded by express middleware or not. Simply including `app.use(...)` causes the crash. Stack and description are now up to date.

**Comment by baer** [comment]
Update: This is most likely an incompatibility between [node-http-proxy](https://github.com/nodejitsu/node-http-proxy) and [express-stormpath](https://github.com/stormpath/express-stormpath). It's not yet clear what the problem is - bug report is now up to date.

**Comment by robertjd** [comment]
Thank you for this information.  The express-stormpath library does place it's `getUser` middleware in front of all requests.  The `getUser` middleware attempts to resolve the current user context and populate `req.user`, but does not return authentication errors if this is not possible.  Instead it just continues down the middleware chain.

Clearly something is causing an unhanded exception, but from this information I can't tell what that might be.  Would you be able to share your project with us so that I can attempt to reproduce?

Thanks!

**Comment by baer** [comment]
Humm, I can't share the project as it is but maybe I can try to reduce it to something I can share. One clue that I can give that I didn't post initially is that the exception happens after nearly 2m. Also, the express logger middleware doesn't log until the exception happens so the app is hanging for the full time.

<img width="482" alt="screen shot 2015-11-03 at 2 42 57 pm" src="https://cloud.githubusercontent.com/assets/940667/10924140/9d049332-8239-11e5-8720-006f3a5a9dde.png">
<img width="432" alt="screen shot 2015-11-03 at 2 43 27 pm" src="https://cloud.githubusercontent.com/assets/940667/10924141/9d06a4ce-8239-11e5-9df3-392a0014e43a.png">
<img width="196" alt="screen shot 2015-11-03 at 2 43 54 pm" src="https://cloud.githubusercontent.com/assets/940667/10924142/9d06b626-8239-11e5-8380-e0a81ebe85be.png">

I will try to create a minimal app that can exhibit the issue.

**Comment by baer** [comment]
@robertjd I found the bug! What I found was that express is inserting `body-parser` into the middleware stack [here](https://github.com/stormpath/express-stormpath/blob/master/lib/stormpath.js#L75). When `request` or `http-proxy` which uses express pipes the data out of request, the stream has already finished but for some reason is not closed/completed (bug in `body parser`?) which causes `request` to sit listening for data until the caller (Chrome) terminates the connection which crashes the app. 

The takeaway is: 
* any app using `espress-stormpath` 100% incompatible with pipe and by extension `http-proxy`
* any app using `stormpath-express` is blocking on all POST requests** which has serious negative perf implications.

The workaround for me is that I can make a new request using `req.body` rather than trying to proxy directly. However, if it is possible it would be great to either put this behind some config OR remove body parsing altogether since it would be both more idiomatic node code and would remove both the internal dep and the registered middleware you require to run `stormpath-express`.

**The offending code code in my app**
```
    req
      .pipe(request[req.method.toLowerCase()](uriRoot + uriFragment, {
        'auth': {
          'user': config.proxyUsername,
          'pass': config.proxyPassword
        }
      }))
      .pipe(res);
```

**Comment by baer** [comment]
Looks like this is not the only issue caused by the `body-parser`.

https://github.com/stormpath/express-stormpath/issues/194

**Comment by typerandom** [comment]
I'm currently looking into this issue.

Thank you @baer for all the work/info you've put into this issue. :beers:

**Comment by robertjd** [comment]
Hello @baer !  JFYI, we have removed the body-parser dependency as of 2.3.7, so please give this a try and let us know how it works for you!  Closing this issue unless we need to re-open.  Thanks again for helping with this one!
