### ISSUE TITLE
"TypeError: undefined is not a function" if no default account store

### ISSUE THREAD

**Issue by robertjd** [stormpath/express-stormpath#212]
If you are seeing this error:

```
TypeError: undefined is not a function
    at /Users/robert/projects/express-stormpath/node_modules/stormpath-config/lib/strategy/EnrichIntegrationFromRemoteConfigStrategy.js:149:9
    at Object.wrapGetResourceResponse [as _wrapGetResourceResponse] (/Users/robert/projects/express-stormpath/node_modules/stormpath/lib/ds/DataStore.js:67:12)
    at onGetResourceRequestResult (/Users/robert/projects/express-stormpath/node_modules/stormpath/lib/ds/DataStore.js:278:13)
    at Request.onRequestResult [as _callback] (/Users/robert/projects/express-stormpath/node_modules/stormpath/lib/ds/RequestExecutor.js:100:14)
    at Request.self.callback (/Users/robert/projects/express-stormpath/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/robert/projects/express-stormpath/node_modules/request/request.js:1035:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/robert/projects/express-stormpath/node_modules/request/request.js:962:12)
    at IncomingMessage.emit (events.js:129:20)
```

then please ensure that you have a default account store that is mapped to the stormpath application that you are specifying in your configuration.

For more information, please see this related issue:

https://github.com/stormpath/stormpath-node-config/issues/11

**Comment by cleechtech** [comment]
how do I set a default account store that is mapped to my stormpath application? I am trying to follow the [node tutorial](https://stormpath.com/blog/angular-node-15-minutes/) and this error is blocking

**Comment by cleechtech** [comment]
Ok had to do this voodoo: 

![screen shot 2015-11-30 at 10 48 59 am](https://cloud.githubusercontent.com/assets/3578908/11481135/5a7c35de-9750-11e5-8b0a-4a9f1f71c660.png)

Not really sure what this does. An explanation would be clutch. Got it to work!

**Comment by rdegges** [comment]
The short answer is that in Stormpath, Applications are decoupled from Account Stores (places where Accounts are stored). This lets you be really flexible with how things work.

For instance, you can create one Directory for each customer you have, and store all of each customer's user Accounts inside of each unique Directory. Then, in order to allow these 'customers' to access your Application (web app or whatever), you'd add these Directories as Account Stores to your Application.

This basically tells Stormpath that if a user tries to login to your Application, what user accounts should Stormpath authenticate?

**Comment by cleechtech** [comment]
Ok cool thank you!

**Comment by robertjd** [comment]
In the new 2.3.4 release, we have friendly error message for this this situation :)

**Comment by cleechtech** [comment]
Awesome!
