### ISSUE TITLE
Cannot navigate to profile view

### ISSUE THREAD

**Issue by cleechtech** [stormpath/express-stormpath#214]
I have an angular app with the run and config defined:

```
app.config(function($stateProvider, $urlRouterProvider){
	$stateProvider
		.state('main', {
			url: "/",
			templateUrl: "templates/main.html",
			controller: 'MainCtrl'
		})
		.state('register', {
			url: "/register",
			templateUrl: "templates/register.html",
		})
		.state('login', {
			url: "/login",
			templateUrl: "templates/login.html",
		})
		.state('profile', {
			url: '/profile',
			controller: 'ProfileCtrl',
			templateUrl: 'templates/profile.html',
			sp: {
				authenticate: true
			}
		});

	$urlRouterProvider.otherwise("/");
});

app.run(function($stormpath){
  $stormpath.uiRouter({
    loginState: 'login',
    defaultPostLoginState: 'main'
  });
});
```
The ProfileCtrl is empty:

```
app.controller('ProfileCtrl', function($scope){

});
```

Then I navigate to the profile view after login using

```
<li if-user ng-class="{active: isActive('/profile')}">
      <a ng-href="/profile">Profile</a>
  </li>
```

This redirects me to `http://localhost:3000/profile#/` but the profile template does not show up (instead my 'main' template stays showed). I am using node.js for the server side. Why is the profile view not rendering? I can provide the server code if necessary. All I really have there is the `app.use(stormpath.init({})`.

**Comment by cleechtech** [comment]
Whoops, this was meant to be posted to the angular.js repo. Did that [here](https://github.com/stormpath/stormpath-sdk-angularjs/issues/86)

**Comment by cleechtech** [comment]
Okay the error renders itself server side:

```
TypeError: Cannot read property 'dataStore' of undefined
    at JwtAuthenticator.authenticate (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express-stormpath/node_modules/stormpath/lib/jwt/jwt-authenticator.js:38:32)
    at Object.module.exports [as getUser] (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express-stormpath/lib/helpers/get-user.js:69:19)
    at stormpathMiddleware (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express-stormpath/lib/stormpath.js:92:13)
    at Layer.handle [as handle_request] (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:312:13)
    at /Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:271:10)
    at /Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:618:15
    at next (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:256:14)
    at cookieParser (/Users/connorleech/Projects/node-angular-stormpath/node_modules/cookie-parser/index.js:40:14)
    at Layer.handle [as handle_request] (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:312:13)
    at /Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:271:10)
```

**Comment by omgitstom** [comment]
@cleechtech Is this an issue on the php sdk?

**Comment by robertjd** [comment]
Hi there, my apologies for the long delay on this reply!

It looks like Stormpath may not be initialized at the time that Angular is trying to make a request to your Express server.  Can you confirm that your Express application is waiting for the `stormpath.ready` event, before starting?

We have this example application, which is a good reference:

https://github.com/stormpath/express-stormpath-angular-sample-project

It shows you how to initialize the Express server with Stormpath, and it also sets up your Express router so that it can serve the Angular assets in the right way (this may help with your profile page issue).

Hope this helps,

Robert

**Comment by cleechtech** [comment]
Oh thank you! I didn't have the stormpath.ready event
