### ISSUE TITLE
Server Crash when Disabling Refresh Tokens

### ISSUE THREAD

**Issue by rdegges** [stormpath/express-stormpath#230]
If I create a Stormpath Application, and disable refresh tokens in the dashboard, eg:

<img width="1057" alt="screenshot 2015-12-11 10 18 32" src="https://cloud.githubusercontent.com/assets/90247/11751804/ac7aa1e2-9ff0-11e5-8786-4a0759281cd8.png">

Then when I go to register a user using the default registration page stuff, my server crashes:

```
nodemon server.js
[nodemon] 1.8.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
/Users/rdegges/Dropbox/Code/testing/timeout/node_modules/express-stormpath/lib/helpers/create-session.js:31
    expires: new Date(passwordGrantAuthenticationResult.refreshToken.body.exp * 1000),
                                                                    ^

TypeError: Cannot read property 'body' of undefined
    at Object.module.exports [as createSession] (/Users/rdegges/Dropbox/Code/testing/timeout/node_modules/express-stormpath/lib/helpers/create-session.js:31:69)
    at /Users/rdegges/Dropbox/Code/testing/timeout/node_modules/express-stormpath/lib/controllers/register.js:247:21
    at /Users/rdegges/Dropbox/Code/testing/timeout/node_modules/express-stormpath/node_modules/stormpath/lib/oauth/password-grant.js:38:7
    at onCreateResourceRequestResult (/Users/rdegges/Dropbox/Code/testing/timeout/node_modules/express-stormpath/node_modules/stormpath/lib/ds/DataStore.js:359:14)
    at Request.onRequestResult [as _callback] (/Users/rdegges/Dropbox/Code/testing/timeout/node_modules/express-stormpath/node_modules/stormpath/lib/ds/RequestExecutor.js:110:7)
    at Request.self.callback (/Users/rdegges/Dropbox/Code/testing/timeout/node_modules/express-stormpath/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/rdegges/Dropbox/Code/testing/timeout/node_modules/express-stormpath/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
[nodemon] app crashed - waiting for file changes before starting...
```

We should fix this so that we aren't assuming the refresh token value is defined.

**Comment by robertjd** [comment]
I can confirm this, it happens when `stormpath.web.register.autoLogin` is `true` and the `refreshTokenTtl` of the OAuth policy is 0 (the provided screenshot shows 1).

**Comment by typerandom** [comment]
This issue has actually already been adressed in this PR #296 (see https://github.com/stormpath/express-stormpath/pull/296/files#diff-20d70a82acdce49356873688f501f1d9R35) so when we merge that, we'll be able to close this one too).
