### ISSUE TITLE
Error: Cannot send secure cookie over unencrypted connection

### ISSUE THREAD

**Issue by xtu** [stormpath/express-stormpath#297]
When I try to login through stormpath default login page, an error is shown. I am using custom login view.
```
2016-02-04 03:25 +00:00: Error: Cannot send secure cookie over unencrypted connection
    at Object.Cookies.set (/distelli/_apps/igosend.igosend-stage.d-96q7if1rqsaff227b826/node_modules/express-stormpath/node_modules/cookies/lib/cookies.js:71:13)
    at module.exports (/distelli/_apps/igosend.igosend-stage.d-96q7if1rqsaff227b826/node_modules/express-stormpath/lib/helpers/create-session.js:22:11)
    at /distelli/_apps/igosend.igosend-stage.d-96q7if1rqsaff227b826/node_modules/express-stormpath/lib/helpers/login-responder.js:48:7
    at /distelli/_apps/igosend.igosend-stage.d-96q7if1rqsaff227b826/node_modules/express-stormpath/lib/helpers/expand-account.js:146:5
    at /distelli/_apps/igosend.igosend-stage.d-96q7if1rqsaff227b826/node_modules/async/lib/async.js:726:13
    at /distelli/_apps/igosend.igosend-stage.d-96q7if1rqsaff227b826/node_modules/async/lib/async.js:52:16
    at done (/distelli/_apps/igosend.igosend-stage.d-96q7if1rqsaff227b826/node_modules/async/lib/async.js:246:17)
    at /distelli/_apps/igosend.igosend-stage.d-96q7if1rqsaff227b826/node_modules/async/lib/async.js:44:16
    at /distelli/_apps/igosend.igosend-stage.d-96q7if1rqsaff227b826/node_modules/async/lib/async.js:723:17
    at /distelli/_apps/igosend.igosend-stage.d-96q7if1rqsaff227b826/node_modules/async/lib/async.js:167:37
    at /distelli/_apps/igosend.igosend-stage.d-96q7if1rqsaff227b826/node_modules/express-stormpath/lib/helpers/expand-account.js:63:9
    at Object.wrapGetResourceResponse [as _wrapGetResourceResponse] (/distelli/_apps/igosend.igosend-stage.d-96q7if1rqsaff227b826/node_modules/express-stormpath/node_modules/stormpath/lib/ds/DataStore.js:84:12)
    at onGetResourceRequestResult (/distelli/_apps/igosend.igosend-stage.d-96q7if1rqsaff227b826/node_modules/express-stormpath/node_modules/stormpath/lib/ds/DataStore.js:273:13)
    at Request.onRequestResult [as _callback] (/distelli/_apps/igosend.igosend-stage.d-96q7if1rqsaff227b826/node_modules/express-stormpath/node_modules/stormpath/lib/ds/RequestExecutor.js:110:7)
    at Request.self.callback (/distelli/_apps/igosend.igosend-stage.d-96q7if1rqsaff227b826/node_modules/express-stormpath/node_modules/stormpath/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/distelli/_apps/igosend.igosend-stage.d-96q7if1rqsaff227b826/node_modules/express-stormpath/node_modules/stormpath/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/distelli/_apps/igosend.igosend-stage.d-96q7if1rqsaff227b826/node_modules/express-stormpath/node_modules/stormpath/node_modules/request/request.js:962:12)
    at emitNone (events.js:72:20)
```

**Comment by robertjd** [comment]
Hello, thank you for the report.  Are you running your application behind an HTTPS proxy?  If so, you may need to add the setting `app.set('trust proxy',true);` on your Express application, so that it can use proxy header information to know that it's behind an HTTPS proxy.

**Comment by xtu** [comment]
Hi @robertjd , when I tried to access the website, I connect directly to the node http server on a specific port. I did not use a HTTPS proxy.

**Comment by robertjd** [comment]
Are you using our configuration options to explicitly enable the HTTPS options of our cookies?  That might cause the problem if you aren't using HTTPS.

**Comment by xtu** [comment]
No, I believe I have not explicitly set that option. I think the default setting should be disabled.

**Comment by xtu** [comment]
I probably found the cause of the issue. I am not using HTTPS but I have set ```accessTokenCookie```. It used work fine until a new change is made on ```cookies``` package. See this commit: https://github.com/pillarjs/cookies/commit/f1b59960a530303b4fdad9516a2904b294959d9a

The issue is fixed by removing ```accessTokenCookie``` for now.
