### ISSUE TITLE
"Possible EventEmitter memory leak detected" 

### ISSUE THREAD

**Issue by mdeggies** [stormpath/express-stormpath#494]
```
(node) warning: possible EventEmitter memory leak detected. 11 stormpath.ready listeners added. Use emitter.setMaxListeners() to increase limit. 
Trace 
at EventEmitter.addListener (events.js:239:17) 
at awaitClientReadyMiddleware (/Users/mattsteele/redacto/node_modules/express-stormpath/lib/stormpath.js:104:11) 
at Layer.handle [as handle_request] (/Users/mattsteele/redacto/node_modules/express/lib/router/layer.js:95:5) 
at trim_prefix (/Users/mattsteele/redacto/node_modules/express/lib/router/index.js:312:13) 
at /Users/mattsteele/redacto/node_modules/express/lib/router/index.js:280:7 
at Function.process_params (/Users/mattsteele/redacto/node_modules/express/lib/router/index.js:330:12) 
at next (/Users/mattsteele/redacto/node_modules/express/lib/router/index.js:271:10) 
at cors (/Users/mattsteele/redacto/node_modules/cors/lib/index.js:178:7) 
at /Users/mattsteele/redacto/node_modules/cors/lib/index.js:228:17 
at originCallback (/Users/mattsteele/redacto/node_modules/cors/lib/index.js:217:15) 
error: Error: Unable to execute http request GET https://api.stormpath.com/v1/applications/1oFNEDlW8GBNJFZ5VSlr4a: read ECONNRESET 
at Request.onRequestResult [as _callback] (/Users/mattsteele/redacto/node_modules/stormpath/lib/ds/RequestExecutor.js:81:21) 
at self.callback (/Users/mattsteele/redacto/node_modules/stormpath/node_modules/request/request.js:200:22) 
at emitOne (events.js:77:13) 
at Request.emit (events.js:169:7) 
at Request.onRequestError (/Users/mattsteele/redacto/node_modules/stormpath/node_modules/request/request.js:831:8) 
at emitOne (events.js:77:13) 
at ClientRequest.emit (events.js:169:7) 
at TLSSocket.socketErrorListener (_http_client.js:259:9) 
at emitOne (events.js:77:13) 
at TLSSocket.emit (events.js:169:7)
```

**Comment by robertjd** [comment]
Can you show us the code that produced that error?  Thanks.

**Comment by mdeggies** [comment]
The person who reported this did not reply back, so I think it's safe to close this one.
