### ISSUE TITLE
Random Expand Issue 

### ISSUE THREAD

**Issue by stergill000** [stormpath/express-stormpath#565]
Have been getting this issue randomly that crashes my project, i can't pinpoint an issue in my code since after restarting the same action that would cause it would work, could it be something with my config or is this an issue with the groups. Any help would be appreciated. 

info: Couldn't expand content_creator@example.com's groups.
C:\Users\sgill\Desktop\NodeStuff\BotStructure\user_interface\node_modules\express-stormpath\lib\controllers\current-user
.js:25
    Object.keys(strippedAccount).forEach(function (property) {
           ^

TypeError: Cannot convert undefined or null to object
    at C:\Users\sgill\Desktop\NodeStuff\BotStructure\user_interface\node_modules\express-stormpath\lib\controllers\curre
nt-user.js:25:12
    at C:\Users\sgill\Desktop\NodeStuff\BotStructure\user_interface\node_modules\express-stormpath\lib\helpers\expand-ac
count.js:88:18
    at Object.wrapGetResourceResponse [as _wrapGetResourceResponse] (C:\Users\sgill\Desktop\NodeStuff\BotStructure\user_
interface\node_modules\stormpath\lib\ds\DataStore.js:66:12)
    at onGetResourceRequestResult (C:\Users\sgill\Desktop\NodeStuff\BotStructure\user_interface\node_modules\stormpath\l
ib\ds\DataStore.js:295:13)
    at Request.onRequestResult [as _callback] (C:\Users\sgill\Desktop\NodeStuff\BotStructure\user_interface\node_modules
\stormpath\lib\ds\RequestExecutor.js:91:14)
    at self.callback (C:\Users\sgill\Desktop\NodeStuff\BotStructure\user_interface\node_modules\stormpath\node_modules\r
equest\request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\Users\sgill\Desktop\NodeStuff\BotStructure\user_interface\node_modules\stormpath\node_
modules\request\request.js:813:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1271:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by mdeggies** [comment]
Hey @stergill000, can you send a zip of your project over to support@stormpath.com, and let us know what this account looks like (eg does it have custom data associated with it)?

**Comment by stergill000** [comment]
Hi @mdeggies I have sent the project files.

**Comment by mdeggies** [comment]
@stergill000, I'm going to close this out, but if you have any more trouble please feel free to open it back up! 

In case anyone else has q's, this was the proposed solution to test the expand groups functionality:

Clone the [express-stormpath sample project](https://github.com/stormpath/express-stormpath-sample-project). Set your API keys and Application href env variables. Add these configs to the server file:

```
app.use(stormpath.init(app, {
  expand: {
    customData: true,
    groups: true
  }
}));
```

Create a route that returns the groups the currently logged in user is a member of. If the user isn't a member of any groups, the empty array will be returned: 

```
router.get('/groups', stormpath.getUser, function(req, res) {

  if (req.user) {
    var groupList = [];

    function iterator(group, next) {
      groupList.push(group);
      next();
    }

    function doneCallback(err) {
      if (!err) {
        res.send(groupList);
      }
    }

    console.log('Found groups for ' + req.user.givenName + ' (' + req.user.email + ')');
    req.user.groups.each(iterator, doneCallback);
  }

});
```
