### ISSUE TITLE
Race condition causing server crash

### ISSUE THREAD

**Issue by baer** [stormpath/express-stormpath#98]
This is the 2nd time I've seen this error and it always goes away on refresh. I'm assuming it's a race condition but I have not dug into it yet. I did catch it when I was in dev mode with long stack traces turned on so this should help you find the issue.

```
TypeError: Cannot read property 'web' of undefined
   at /Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express-stormpath/lib/authentication.js:62:47
   at Layer.handle [as handle_request] (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/layer.js:95:5)
   at next (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/layer.js:95:5)
   at /Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/index.js:330:12)
   at next (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/index.js:271:10)
   at favicon (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/serve-favicon/index.js:72:7)
   at Layer.handle [as handle_request] (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/layer.js:95:5)
---------------------------------------------
   at serveStatic (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/serve-static/index.js:114:12)
   at Layer.handle [as handle_request] (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/index.js:312:13)
   at /Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/index.js:330:12)
   at next (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/index.js:271:10)
   at /Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express-stormpath/lib/stormpath.js:77:7
   at /Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express-stormpath/node_modules/async/lib/async.js:697:13
   at /Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express-stormpath/node_modules/async/lib/async.js:52:16
---------------------------------------------
   at next (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/index.js:198:7)
   at urlencodedParser (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/body-parser/lib/types/urlencoded.js:88:40)
   at Layer.handle [as handle_request] (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/index.js:312:13)
   at /Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/index.js:330:12)
   at next (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/index.js:271:10)
   at Function.handle (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/index.js:176:3)
   at router (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/router/index.js:46:12)
---------------------------------------------
   at new Server (_http_server.js:226:10)
   at Object.exports.createServer (http.js:44:10)
   at EventEmitter.listen (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/express/lib/application.js:616:21)
   at Object.<anonymous> (/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/app.js:10:5)
   at Module._compile (module.js:434:26)
   at Object.Module._extensions..js (module.js:452:10)
   at Module.load (module.js:355:32)
   at Function.Module._load (module.js:310:12)
   at Function.Module.runMain (module.js:475:10)
```

**Comment by typerandom** [comment]
@baer Thank you for the stack trace! :beer: 

This issue will most likely be resolved with PR #122. This PR will use our new way of loading configuration and will make it so that the integration will no longer be able to be initialized at a state to which you are referring.

Meanwhile, if you're able to share the configuration you're using (omitting any sensitive values) then that would be very valuable.

**Comment by baer** [comment]
Sure thing! I know that v2 config is not yet very well documented so I may just be using a bad config value.

```js
  app.use(stormpath.init(app, {
    website: true,
    client: {
      apiKey: {
        id: config.stormpath.id,
        secret: config.stormpath.secret
      }
    },
    application: {
      href: config.stormpath.url
    },
    web: {
      register: {
        fieldOrder: [ "givenName", "surname", "email", "password", "passwordConfirm" ]
      }
    }
  }));
```

**Comment by typerandom** [comment]
Thank you.

The configuration looks correct. And since you're seeing an intermittent error, it points to the issue that we've fixed in the up and coming pull request.

**Comment by robertjd** [comment]
Now that #122 is released, the way around this problem is to use the ready event and defer the binding of your server:

```
app.use(stormpath.init(app, { /** config **/}));

app.on('ready', function() {
  app.listen(port)
});
```

**Comment by baer** [comment]
Oh great! But, where does that `ready` event come from? It's not in the Express documentation anywhere.

http://expressjs.com/4x/api.html#app.onmount
